export const DASHBOARD_SAVE_STARTED = 'dashboards-view/DASHBOARD_SAVE_STARTED';
export const DASHBOARD_SAVE_COMPLETED = 'dashboards-view/DASHBOARD_SAVE_COMPLETED';
export const DASHBOARD_SAVE_REJECTED = 'dashboards-view/DASHBOARD_SAVE_REJECTED';
export const DASHBOARD_REMOVE_STARTED = 'dashboards-view/DASHBOARD_REMOVE_STARTED';
export const DASHBOARD_REMOVE_COMPLETED = 'dashboards-view/DASHBOARD_REMOVE_COMPLETED';
export const DASHBOARD_REMOVE_REJECTED = 'dashboards-view/DASHBOARD_REMOVE_REJECTED';
export const UPDATE_DASHBOARD_MODEL = 'dashboards-view/UPDATE_DASHBOARD_MODEL';
