export const USER_LOGIN_COMPLETED = 'auth/USER_LOGIN_COMPLETED';
export const USER_LOGIN_STARTED = 'auth/USER_LOGIN_STARTED';
export const USER_LOGIN_REJECTED = 'auth/USER_LOGIN_REJECTED';
export const USER_LOGOUT_COMPLETED = 'auth/USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_STARTED = 'auth/USER_LOGOUT_STARTED';
export const USER_LOGOUT_REJECTED = 'auth/USER_LOGOUT_REJECTED';
