export const DASHBOARD_LIST_REJECTED = 'header/DASHBOARD_LIST_REJECTED';
export const DASHBOARD_LIST_STARTED = 'header/DASHBOARD_LIST_STARTED';
export const DASHBOARD_LIST_COMPLETED = 'header/DASHBOARD_LIST_COMPLETED';
export const DASHBOARD_UPDATED = 'header/DASHBOARD_UPDATED';
